//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace praks
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {

            static Employee emp;

            public static Employee CrtEmployee(int ID, string Surname, string Name, string Patronymic, int TitleID)
            {
                emp = new Employee();
                emp.Id = ID;
                emp.Surname = Surname;
                emp.Name = Name;
                emp.Patronymic = Patronymic;
                emp.TitleId = TitleID;
                emp.Telephone = "Не задано";
                emp.Email = "Не задано";

                return emp;
            }
        public int Id { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public int TitleId { get; set; }
    
        public virtual Title Title { get; set; }
    }
}
